#include "arduino_secrets.h"

// M5Atom - Version: Latest
#include <M5Atom.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Arduino_Cloud_M5_iot_farm"
  https://create.arduino.cc/cloud/things/57818426-7bbe-4bee-9ea4-dae173670783

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool relay_1_state;
  bool relay_2_state;
  bool relay_3_state;
  bool relay_4_state;

  float TDS_water;
  float T_air;
  float RH_air;
  float T_water;
  float Ev_ambient;
  bool  SEN0503_state;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

// #include <multi_channel_relay.h>

// Multi_Channel_Relay relays;

#include <Adafruit_Sensor.h>
#include <Adafruit_AM2320.h>

Adafruit_AM2320 air_T_RH_sensor = Adafruit_AM2320();

// #include <OneWire.h>
// 
// #define water_T_sensor_pin 23
// 
// OneWire ds(water_T_sensor_pin);

#include <DFRobot_B_LUX_V30B.h>

#define Ev_sensor_SCL_pin 22
#define Ev_sensor_SDA_pin 19

DFRobot_B_LUX_V30B Ev_sensor(13, Ev_sensor_SCL_pin, Ev_sensor_SDA_pin);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  M5.begin(true, false, true);
  M5.dis.fillpix(0x00ff00);

  pinMode(33, INPUT);
  air_T_RH_sensor.begin();
  Ev_sensor.begin();
  pinMode(23, INPUT);
}

void loop() {
  ArduinoCloud.update();
  // Your code here

  // relays.channelCtrl(relay_1_state << 0 | relay_2_state << 1 | relay_3_state << 2 | relay_4_state << 3);

  TDS_water = getTdsValue();
  T_air = air_T_RH_sensor.readTemperature();
  RH_air = air_T_RH_sensor.readHumidity();
  // T_water = getTemp();
  Ev_ambient = Ev_sensor.lightStrengthLux();
  // SEN0503_state = digitalRead(23);

  delay(50);
}

/*
  Since relay_1_state is READ_WRITE variable, onRelay1StateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay1StateChange()  {
  // Add your code here to act upon relay_1_state change
}

/*
  Since relay_2_state is READ_WRITE variable, onRelay2StateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay2StateChange()  {
  // Add your code here to act upon relay_2_state change
}

/*
  Since relay_3_state is READ_WRITE variable, onRelay3StateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay3StateChange()  {
  // Add your code here to act upon relay_3_state change
}

/*
  Since relay_4_state is READ_WRITE variable, onRelay4StateChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay4StateChange()  {
  // Add your code here to act upon relay_4_state change
}
